### ISSUE TITLE
Benchmark tests for Spine Toolbox performance improvements

### ISSUE THREAD

**Issue by suvayu** [ESI-FAR/Mopo-arrow_sqlite#3]
- [~Analysis & plan~](https://github.com/ESI-FAR/wiki/blob/main/mopo/spine/spine-tools-blobs.md)
- [Upstream discussion of analysis](https://github.com/spine-tools/Spine-Toolbox/discussions/2682)

---

Spine DB stores `parameter_value`s as JSON blobs in the database.  This is fine as long as the blobs are small.  When blobs are large objects like a time series, or a shape file. Loading the value can have significant delays, and this freezes the UI (or at least the user can't see something is happening in the background) while the blob is loaded and parsed.

There are several expensive step in this process:
- Retrieve the blob from the DB (we don't know beforehand the size of the blob).  This is an uninterruptible asynchronous step
- Accessing the DB requires disk I/O or connecting over the network (both are potentially slow)
- Parsing and allocating memory to store the object (either as Python/Arrow objects)
- Spine DB API overhead in creating the `Timeseries` data structure

## Documentation
- ESI-FAR/wiki#61 

## Different cases that should be benchmarked

Create example scripts that replicate and benchmark different options:
- [x] #7 (current)
  - ~first pass w/o a DB: [`binary_cols.py`](https://github.com/ESI-FAR/Mopo-arrow_sqlite/blob/main/binary_cols.py)~
- [x] #9
- [ ] #6 (JSON query using DB)
- [x] #5 (dedicated tables)
- [x] external file: large objects are stored as files on disk (#4)
- [x] ~additional common table: still has blobs, but other columns to filter for type or parameter~

## What to benchmark?

- [x] Performance cost of retrieval
  - How to prevent caching during benchmarking? ⚠️ TODO
- [x] ~Can retrieval be batched?~
  - batches of what? ⚠️ TODO
- [x] Can retrieval be resource efficient by filtering?
  - how does that work? ⚠️ TODO
- [x] #4

## Possible data types

`parameter_value`s can be of [various types](https://spine-database-api.readthedocs.io/en/latest/parameter_value_format.html).  (the first two are not relevant here, included for completeness)

- ~date time: single value~
- ~duration: single value~
- [ ] time pattern: range indexed time series
- [ ] time series: 4 variations, including sparse
- [ ] array: maybe of specified types
- [ ] map: a generic way to store some combination of the above types in one field 🤬 

## Example datasets

- [x] A dataset with various examples from Juha, on [Mopo sharepoint](https://vttgroup.sharepoint.com/:f:/r/sites/EUESIMopo/Shared%20Documents/General/WP3%20Toolbox%20CONFIDENTIAL/data_examples?csf=1&web=1&e=HQTC6V)

## Spine data structure

https://github.com/energy-modelling-workbench/spine-data-model#spine-data-model

---

For more notes on when/how these are used, see ESI-FAR/wiki#44 (the visualisation issue)

**Comment by suvayu** [comment]
Summarised in: https://github.com/ESI-FAR/Mopo-spinedb_api-benchmarks
