### ISSUE TITLE
Benchmark retrieval of different `spinedb_api` data types

### ISSUE THREAD

**Issue by OleMussmann** [ESI-FAR/Mopo-arrow_sqlite#8]
### Tasks
- [ ] Explore `BB_data.sqlite` for typical and worst-case amounts of data per data type,
  -  where to find them?

- [ ] Write code to read database and retrieve data for all (current) data types.
  - [ ] Date-time
  - [ ] Duration
  - [ ] Time-pattern
  - [ ] Time-series
  - [ ] Array
  - [ ] Map

- [ ] Profile the code and see where bottlenecks are

**Comment by suvayu** [comment]
Maybe this should be consolidated into #7?

**Comment by suvayu** [comment]
Possible encodings for the index part of map types:
- [dictionary encoded array](https://arrow.apache.org/docs/python/data.html#dictionary-arrays) (equivalent to a `pandas.Categorical`)
- [Run Length Encoding](https://en.wikipedia.org/wiki/Run-length_encoding): [`RunEncodedArray` in PyArrow](https://arrow.apache.org/docs/python/generated/pyarrow.RunEndEncodedArray.html#pyarrow-runendencodedarray)

**Comment by OleMussmann** [comment]
Merged into #7
